name: Build and Deploy Code

on:
  push:
    branches:
      - "main"
      - "dev"
  pull_request:
    branches:
      - "test_branch"

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/setup-node@v2
      - name: Say hi to janitha
        run: echo "hellow janitha"


