name: Build and Deploy Code

on:
  push:
    branches:
      - "main"
      - "dev"
  pull_request:
    branches:
      - "test_branch"

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: Say hi to janitha
        run: echo "hellow janitha"
      - name: Intsall python version 3.8
        with:
          python-version: "3.9"
      - name: Update pip
        run: python -m pip install --upgrade pip
      - name: Install all dependencies
        run: pip install -r requirements.txt
      - name: Test with pytest
        run: |
          pip install pytest
          pytest



